#!/bin/sh
gcc -DHASH_FUNCTION=HASH_SAX -g -o parser ../src/y.tab.c ../src/lex.yy.c ../src/symbol_table.c ../src/ast.c parser.c
gcc -DHASH_FUNCTION=HASH_SAX -g -o ast ../src/y.tab.c ../src/lex.yy.c ../src/symbol_table.c ../src/ast.c ast.c
gcc -DHASH_FUNCTION=HASH_SAX -g -o eval ../src/ast.c ../src/symbol_table.c ../src/propositional_logic.c ../src/y.tab.c ../src/lex.yy.c eval.c
./parser
./ast
./eval
rm parser ast eval

